

########### hwaseong dev db postgres

db.eas.driver=org.postgresql.Driver
db.eas.dialect=org.hibernate.dialect.PostgreSQLDialect
db.eas.url=jdbc:postgresql://${DB_EAS_HOST}:${DB_EAS_PORT}/uctc2
db.eas.username=${DB_EAS_USERNAME}
db.eas.password=${DB_EAS_PASSWORD}
db.eas.ddl.auto=none


########### hwaseong dev db mysql

db.sensor.driver = com.mysql.cj.jdbc.Driver
db.sensor.dialect = org.hibernate.dialect.MySQLDialect
db.sensor.url = jdbc:mysql://${DB_SENSOR_HOST}:${DB_SENSOR_PORT}/dw?useUnicode=true&serverTimezone=Asia/Seoul
db.sensor.username = ${DB_SENSOR_USERNAME}
db.sensor.password = ${DB_SENSOR_PASSWORD}
db.sensor.ddl.auto = none


########### hwaseong db oracle

db.sms.driver = oracle.jdbc.driver.OracleDriver
db.sms.dialect = org.hibernate.dialect.Oracle9iDialect
db.sms.url = jdbc:oracle:thin:@${DB_SMS_HOST}:${DB_SMS_PORT}/uctc2
db.sms.username = ${DB_SMS_USERNAME}
db.sms.password = ${DB_SMS_PASSWORD}
db.sms.ddl.auto = none


###### cryptsvr

cryptsvr.system.key = ${CRYPT_SYSTEM_KEY}
cryptsvr.system.secret = ${CRYPT_SYSTEM_SECRET}
cryptsvr.crypt.type = ARIA
cryptsvr.decrypt = /decrypt
cryptsvr.encrypt = /encrypt
cryptsvr.api.address = ${CRYPT_API_ADDRESS}


###### weather api

api.weather.info=http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0/getVilageFcst?ServiceKey={API_KEY}&pageNo=1&dataType=JSON&base_date={BASE_DATE}&base_time={BASE_TIME}&nx={NX}&ny={NY}
api.weather.key=${WEATHER_API_KEY}
api.weather.grid.x=57
api.weather.grid.y=119


api.weather.warn.info = http://apis.data.go.kr/1360000/WthrWrnInfoService/getWthrWrnList?ServiceKey={API_KEY}&numOfRows=10&pageNo=1&dataType=JSON&stnId={STN}&fromTmFc={FROM_DATE}
api.weather.warn.stn.id = 108


###### iot

iot.url = ${IOT_SERVER_URL}
iot.apiKey = ${IOT_API_KEY}
iot.device.list = /api/v1.0/mgt/device?clientCd={CLIENT_CD}&rows=1000
iot.device.clientCd = HWA

iot.stat.list = /api/v1.0/device/{dvcPkId}/stream/{streamPkId}/statistic
iot.raw.list = /api/v1.0/device/{dvcPkId}/stream/{streamPkId}/rawdata
iot.latest.list = /api/v1.0/device/{dvcPkId}/stream/{streamPkId}/latest
